### PR TITLE
Android support

### PR DESCRIPTION
**Pull request by micuat**
Realizing [this issue](https://github.com/xfleckx/LSL4Unity/issues/7).

I added Android library (which I compiled by myself - not sure [the official release](ftp://sccn.ucsd.edu/pub/software/LSL/SDK/) works as well) and an Android manifest, which was a tricky part (without manifest, the app cannot use network interfaces and LSL crashes with a weird error. It took me for a while to figure this out :cry:).

I'm not sure if this should be immediately merged or not because the `Plugin` folder needs to be moved directly under Assets manually. I think it's better to restructure the repository as a standalone Unity project and wrap it as a `.unitypackage`. Also my edit of `LSL.cs` is somewhat nasty...

### CODE REVIEW

**Comment by micuat** [comment]
Actually manifest is not needed - there is an option called Configuration -> Internet Access in Player Settings. This is Auto by default but changing it to Require seems to overwrite the manifest. My guess is when Unity Editor detects networking functions it will automatically add a permission to manifest but in my case networking happens in the `.so` so the permission wasn't added.

**Comment by xfleckx** [comment]
Hy,

thanks for your work! I will review the changes...

Have you tried to put the plugin under **LSL4Unity/Plugins/Android...**? Considering the Unity documentation [here](https://docs.unity3d.com/Manual/SpecialFolders.html).
I would expect that this should work...  !? Could you try this please?

**Comment by xfleckx** [comment]
We can add the permission automatically through an InitializeOnLoad Method... 

I see the problem, I tried it also with the all LSL libraries... for some strange reason, Unity won't find it even if I put them into the Plugin directory... so I stick to my workaround using a custom path for the DLLImport Attributes. 

I don't like the Idea of creating a whole Unity project around this asset package. 
I would like to have the ability to use this repository as a Submodule (git stuff). 
Also it clutters the whole thing with project settings and stuff no one really needs at the moment of importing this package. Creating an asset package should be done when the project is declared as stable for a certain version... which still needs some work... at least from my side.

**But** I will try to manage the problem through implementing a little procedure which moves the Android stuff from Assets/LSL4Unity/Plugins/Android to Plugins/Android when the asset package get's importet.

**Comment by micuat** [comment]
In Android, `DLLImport` should not include path. It doesn't accept `lib` prefix and `.so` extension so you only need `lslAndroid`. It seems libraries do not have to be inside `Plugins/Android` but can be placed wherever (I'm using the latest version 5.4.1.f1). Maybe you need to enable a checkbox in Unity Editor - if you select `liblslAndroid.so` in the project explorer, the inspector shows up.

Also manifest is not needed as long as Internet option is enabled in the player settings. So there is no need to move the `Plugins` folder nor making unitypackage (I agree that submodule is way easier to manage versions).

**Comment by xfleckx** [comment]
Ok cool, so no need for more changes... I guess I will accept the pull request, remove the manifest and take care that the Internet options gets enabled automaticaly... Right?

**Comment by micuat** [comment]
Give me another day to clean up this PR. Also I should open a separate PR to add <double> Write function.

**Comment by xfleckx** [comment]
Yes that's a good idea.. :) but forget about the double parameter.. I will fix this :) to avoid fixing the merge conflict :)

**Comment by micuat** [comment]
moved to https://github.com/xfleckx/LSL4Unity/pull/10

**Pull request closed without merging**
